#!/bin/bash
#HPCI -n my_code
#HPCI -v 1.2.3
#HPCI -u http://www.example.com
#HPCI -x export SOMETHING=3
#HPCI -l ncarenv
#HPCI -l gnu                # modules can be loaded on same line or multiple lines 
#HPCI -p netcdf             # even if they are prerequisite modules, however, the order
#HPCI -p ncl                # of their dependency must be respected

# terminate this script immediately should anything go wrong
set -e

echo Value of SOMETHING=$SOMETHING
echo This script pretends to be installing 
echo $HPCI_SW_NAME version v${HPCI_SW_VERSION} in ${HPCI_SW_DIR}.
echo And modules in one of $HPCI_MOD_DIR
echo or $HPCI_MOD_DIR_CDEP
echo or $HPCI_MOD_DIR_IDEP
echo using prerequisite module $HPCI_MOD_PREREQ

echo PRETENDING TO BE RUNNING: ./configure --prefix=$HPCI_SW_DIR
echo PRETENDING TO BE RUNNING: make and make install

# Create the module directory, if needed
# if this were compiler-independent module $HPCI_MOD_DIR_IDEP would have been used
mkdir -p $HPCI_MOD_DIR_CDEP/$HPCI_SW_NAME/

# Create the module with the following template
cat << EOF > $HPCI_MOD_DIR_CDEP/$HPCI_SW_NAME/${HPCI_SW_VERSION}.lua
require("posix")

whatis("$HPCI_SW_NAME v$HPCI_SW_VERSION")

help([[
This module loads my_code.
See http://my_code.example.com/ for details.
]])

local verpath = "$HPCI_SW_DIR"                    -- specific version path
local binpath = pathJoin(verpath, "bin")          -- internal python libs
-- similarly for includes or others

prepend_path("PATH", binpath)

prereq($HPCI_MOD_PREREQ)
EOF

