scratch_tree: /glade/scratch/${USER}/ch
sw_install_dir: /glade/u/apps/ch/opt/
mod_install_dir: ~/CheyenneModules/${SUDO_USER}/CheyenneModules/chey
sw_install_struct:  ${LMOD_FAMILY_MPI}/${LMOD_FAMILY_MPI_VERSION}/${LMOD_FAMILY_COMPILER}/${LMOD_FAMILY_COMPILER_VERSION}/
mod_install_struct: ${LMOD_FAMILY_MPI}/${LMOD_FAMILY_MPI_VERSION}/${LMOD_FAMILY_COMPILER}/${LMOD_FAMILY_COMPILER_VERSION}/
