scratch_tree: /picnic/scratch
sw_install_dir: /picnic/u/apps/la/opt/
mod_install_dir: ~/CheyenneModules/${SUDO_USER}/CheyenneModules/la
script_repo: ~/.hpcinstall/chey-install-scripts
sw_install_struct: ${LMOD_MPI_COMPILER}/${LMOD_MPI_VERION}/${LMOD_FAMILY_COMPILER}/${LMOD_COMPILER_VERION}/
mod_install_struct: ${LMOD_MPI_COMPILER}/${LMOD_MPI_VERION}/${LMOD_FAMILY_COMPILER}/${LMOD_COMPILER_VERION}/
