scratch_tree: /glade/scratch
sw_install_dir: /glade/apps/opt
mod_install_dir: /glade/apps/opt/modulefiles/
environment_prefix: ml python
git_cmd: /glade/apps/opt/git/2.3.0/gnu/4.8.2/bin/git
script_repo: ~/.hpcinstall/ys-install-scripts
