#!/usr/bin/env python

import optparse # cruder than others, but compatible with older versions of python
import os, stat, shutil, sys, subprocess, yaml
import tee

compiler_modules = ["gnu", "intel", "pgi", "pathscale", "pgi", "cuda", "sun"]

use_parent_shell = os.environ['SHELL'] + " -c "    # workaround for fixing tcsh module problem, see https://github.com/NCAR/HPCinstall/issues/6
files_to_archive = [os.path.realpath(__file__)]    # logs and other files to preserve, initialized with this script
HPCi_log = "log.hpcinstall.txt"
default_dirs = {}                                  # just make it global

def parse_config_file():
    config_filename = ( os.path.dirname(os.path.realpath(__file__)) + # directory where this script is
                        "/config.hpcinstall.yaml" )
    list_of_dirs =['scratch_tree', 'sw_install_dir', 'mod_install_dir' ]
    try:
        config = yaml.safe_load(open(config_filename))
        if not config:
            raise AttributeError()
        for dirname in list_of_dirs:
            default_dirs[dirname] = config[dirname] + "/"
    except KeyError:
        print >> sys.stderr, "Error:", config_filename, "does not contain the expected fields", list_of_dirs
        sys.exit(1)
    except IOError as e:
        print >> sys.stderr, e
        print >> sys.stderr, "Cannot set", list_of_dirs, "-- ABORTING"
        sys.exit(1)

def separator(msg=""):
    print msg.center(80,"-")

def parse_installscript_filename(filename):
    sw_structure = filename.split("-")
    if len(sw_structure) !=3:
        print "The software name and version must be specified as <software-version>. Got '" + filename + "' instead"
        sys.exit(1)
    return sw_structure[1] + "/" + sw_structure[2]

def parse_command_line_arguments():
    usage = ("usage: %prog [options] <software-version>\n" +
             "Required:\n" +
             "  <software-ver> script in the current directory which\n" +
             "                 does the build and install (do not use\n" +
             "                 './', relative nor fully qualified paths)")
    parser = optparse.OptionParser(usage)
    parser.add_option("-c", "--csgteam", action="store_true", default=False, help='Install as csgteam (default: False)')
    parser.add_option("-f", "--force", action="store_true", default=False, help='Force overwrite of existing install (default: False)')
    (options, args) = parser.parse_args()
    if len(args) != 1:
        parser.print_help()
        sys.exit(1)
    install_script = args[0]
    if not os.path.isfile(install_script) or "/" in install_script:
        parser.print_help()
        sys.exit(1)
    return install_script, options

def ask_confirmation_for(options, msg):
    if options.csgteam:
        print msg,
        answer = sys.stdin.readline()
        print
        if answer.lower().strip() != "yes":
            print "You did not say an ethusiastic 'yes', aborting..."
            sys.exit(1)

def get_variables(options, my_program, my_compiler):
    if options.csgteam:
        if os.environ['USER'] != "csgteam":
            ask_confirmation_for(options, "Should sudo into 'csgteam' to install as such. Continue anyway? ")
        prefix     = default_dirs["sw_install_dir"]  + my_program + "/" + my_compiler
        modulefile = default_dirs["mod_install_dir"] + my_program + ".lua"
    else:
        if "INSTALL_TEST_BASEPATH" in os.environ:
            basepath = os.environ['INSTALL_TEST_BASEPATH']
        else:
            basepath = default_dirs["scratch_tree"] + os.environ['USER'] + "/test_installs/"
        prefix = basepath + "/" + my_program + "/" + my_compiler
        modulefile = basepath + "/modulefiles/" + my_program + ".lua"

    if os.path.exists(prefix) and not options.force:
        print "File already exists", prefix
        sys.exit(1)
    if os.path.exists(modulefile) and not options.force:
        print "File already exists", prefix
        sys.exit(1)
    return prefix, modulefile

def set_variables_and_warn(prefix, modulefile, options, install_script):
    print "Setting environmental variables:"
    print "INSTALL_DIR     =", prefix
    print "MODULE_FILENAME =", modulefile
    print
    ask_confirmation_for(options, "This will attempt global install in " + prefix + 
                         " by running ./" + install_script + " as " + os.environ['USER'] + ". Continue? ")
    os.environ['INSTALL_DIR'] = prefix
    os.environ['MODULE_FILENAME'] = modulefile

def start_logging_current_session(log=HPCi_log, continuation=False):
    if continuation:
        tee.append_out_to(log)
    else:
        tee.overwrite_out_to(log)
        files_to_archive.append(log)
def stop_logging_current_session():
    tee.close_all_files()

def subcall(modules_to_load, command, log=None, use_popen = False):
    str_cmd = use_parent_shell + "'" + modules_to_load + command + "'"
    if log:
        str_cmd += " &> " + log
    if use_popen:
        return subprocess.Popen(str_cmd, stderr=subprocess.STDOUT, stdout = subprocess.PIPE, shell=True)
    else:
        return subprocess.call(str_cmd, shell=True)

def parse_compiler_and_log_full_env(modules_to_load):
    env_log = "log.env.txt"
    print "Saving environment status in", env_log, "...",
    subcall(modules_to_load, "env", env_log)
    print "Done."
    files_to_archive.append(env_log)

    module_log = "log.modules.txt"
    print "Saving module list in", module_log, "...",
    subcall(modules_to_load, "module list", module_log)
    print "Done.\n"
    loaded_compiler = []
    files_to_archive.append(module_log)
    for line in open(module_log):
        for c in compiler_modules:
            if c in line:
                for single_module in line.split():
                    if single_module.startswith(c + "/"):
                        loaded_compiler.append(single_module)
    compiler = ""
    if len(loaded_compiler) == 1:
        compiler = loaded_compiler[0]
    elif len(loaded_compiler) > 1:
        compiler = loaded_compiler[0]
        print "Warning, more than one compiler found:", loaded_compiler, "-- Using only the first."
    return compiler

def parse_installscript_for_modules(install_script):
    warning = ""
    executing_lines = []
    for line in open(install_script):
        if "module" in line or "ml" in line:
            if line.startswith("#"):
                exe_line = line.replace("#", "", 1).strip()
                executing_lines.append(exe_line)
            else:
                warning += line
    if warning != "":
        separator(" POSSIBLY PROBLEMATIC COMMANDS IN ./" + install_script + " ")
        print warning,
        separator()
        ask_confirmation_for(options, "Would you like to run anyway? ")
        print
    modules_to_run = "; ".join(executing_lines)
    if len(modules_to_run) > 0:
        modules_to_run += "; "
    return modules_to_run

def execute_installscript(modules_to_load, install_script):
    current_perm = os.stat(install_script)
    os.chmod(install_script, current_perm.st_mode | stat.S_IEXEC)
    print "Running ./" + install_script, "..."
    stop_logging_current_session()                                  # log the output of the script in a different dir
    log = "log." + install_script  + "-" + str(os.getpid()) + ".txt"
    start_logging_current_session(log=log)
    p = subcall(modules_to_load, "./" + install_script, use_popen=True)
    process_output = " "
    while process_output != "":               # continue while the process is running, it'll be "" when EOF is reached
        process_output = p.stdout.readline()  # needs to do this instead of using subprocess.call to allow 
        print process_output,                 # 'tee' to log the process output
    p.poll()
    stop_logging_current_session()
    files_to_archive.append(log)
    start_logging_current_session(continuation=True)
    print "Done running ./" + install_script, "- exited with code", p.returncode
    files_to_archive.append(install_script)

def archive_in(prefix):
    build_dir = prefix + "/BUILD_DIR/"
    if not os.path.exists(build_dir):
    	os.makedirs(build_dir)
    for somefile in files_to_archive:
    	shutil.copyfile(somefile, build_dir + os.path.basename(somefile))

# execution starts here
parse_config_file()
install_script, options = parse_command_line_arguments()
my_program = parse_installscript_filename(install_script)
modules_to_load = parse_installscript_for_modules(install_script)
my_compiler = parse_compiler_and_log_full_env(modules_to_load)
prefix, modulefile = get_variables(options, my_program, my_compiler)
start_logging_current_session()
set_variables_and_warn(prefix, modulefile, options, install_script)
execute_installscript(modules_to_load, install_script)
stop_logging_current_session()
archive_in(prefix)
