#!/bin/bash
#HPCI -n hpcinstall
#HPCI -n 1.0rc
#HPCI -x ml git
#HPCI -u https://github.com/NCAR/HPCinstall/

# saving current status of the repo
branch=$(git symbolic-ref --short -q HEAD)
if [ -z "${branch}" ]; then
  tag=$(git name-rev --name-only --tags --no-undefined HEAD 2>/dev/null | sed -n 's/^\([^^~]\{1,\}\)\(\^0\)\{0,1\}$/\1/p')
  branch=tags/${tag}
fi

# switching to desired version
git checkout -q tags/v${HPCI_SW_VERSION}

tag_checkedout=$?
if [ $tag_checkedout -ne 0 ]; then
  echo "Can't checkout version ${HPCI_SW_VERSION} aborting"
  exit $tag_checkedout
fi

# if successfull, create directory and copy relevant files
mkdir -p $HPCI_SW_DIR
cp hpcinstall tee.py tee.pyc README.md config.hpcinstall.yaml $HPCI_SW_DIR

# copy also this directory (library dependence)
cp -r yaml $HPCI_SW_DIR

echo You may restore the previous status of the repo with
echo git checkout $branch
